spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exchange?serverTimezone=Europe/Moscow
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  #  jpa:
  #    show-sql: true
  #    hibernate.ddl-auto: none

  liquibase:
    url: jdbc:mysql://localhost:3306/exchange?serverTimezone=Europe/Moscow
    change-log: classpath:db/changelog/db.changelog-master.yaml
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
